{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "17ee205e-9e6e-4b3f-beac-5fa156899e91",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Aspect Ratio = 1.58\n",
      "Major Radius = 512.00\n",
      "Minor Radius = 325.00\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "8716924c47c84c50b34a2f5abe886a23",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(VBox(children=(HBox(children=(Checkbox(value=False, description='Axes', indent=False, _dom_clasâ€¦"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import numpy as np\n",
    "import paramak\n",
    "from paramak import shape\n",
    "from paramak.utils import union_solid\n",
    "import paramak_tfcoil_rectroundcorner\n",
    "from reactor_components.tf_coil_round_corners import ToroidalFieldCoilRectangleRoundCorners\n",
    "from typing import List, Union, Optional \n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "class NegativeTriangularityReactor(paramak.Reactor):\n",
    "    \"\"\"\n",
    "    New class of reactor that builds a negative triangularity tokamak model. \n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "    def __init__(self,\n",
    "        inner_tf_coil_thickness: float,\n",
    "        vacuum_vessel_thickness: float,\n",
    "        central_shield_thickness: float,\n",
    "        wall_to_plasma_gap: float,\n",
    "        plasma_radial_thickness: float,\n",
    "        elongation: float,\n",
    "        triangularity: float,\n",
    "        inner_wall_thickness: float,\n",
    "        blanket_thickness: float,\n",
    "        rear_wall_thickness: float,\n",
    "        divertor_radial_thickness: float,\n",
    "        divertor_height_full: float,\n",
    "        number_of_coils: int,\n",
    "        tf_width: float,\n",
    "        pf_coil_heights: Optional[Union[float,list]],\n",
    "        pf_coil_widths: Optional[Union[float,list]],\n",
    "        pf_coil_center_points: Optional[Union[list,tuple]],\n",
    "        pf_coil_casing_thickness: Optional[float],     \n",
    "\n",
    "        rotation_angle: float,\n",
    "\n",
    "        inner_bore_radius: Optional[float] = 5,\n",
    "        port_side_length: Optional[float] = 20,\n",
    "        port_thickness: Optional[float] = 20,\n",
    "        show_plasma: bool = True,\n",
    "        low_aspect: bool = False,\n",
    "        outer_tf_coil_thickness: float = None,\n",
    "        inner_pf_coil_width: Optional[Union[float, List[float]]] = None,\n",
    "        inner_pf_coil_height: Optional[Union[float, List[float]]] = None,\n",
    "        inner_pf_coil_case_thickness: Optional[Union[float, List[float]]] = None,\n",
    "        inner_pf_coil_center_points: Optional[Union[float, List[float]]] = None,\n",
    "        ports_enabled: Optional[bool] = False,\n",
    "        pf_enabled: Optional[bool] = False,\n",
    "        **kwargs,\n",
    "\n",
    "        ):\n",
    "\n",
    "        super().__init__([])\n",
    "        self.method = 'trelis'\n",
    "        self._inner_tf_coil_thickness = inner_tf_coil_thickness\n",
    "        self._vacuum_vessel_thickness = vacuum_vessel_thickness\n",
    "        self._central_shield_thickness = central_shield_thickness\n",
    "        self._wall_to_plasma_gap = wall_to_plasma_gap\n",
    "        self._plasma_radial_thickness = plasma_radial_thickness\n",
    "        self._elongation = elongation\n",
    "        self._triangularity = -1 * abs(triangularity)\n",
    "        self._inner_wall_thickness = inner_wall_thickness\n",
    "        self._blanket_thickness = blanket_thickness\n",
    "        self._rear_wall_thickness = rear_wall_thickness\n",
    "        self._divertor_radial_thickness = divertor_radial_thickness\n",
    "        self._inner_pf_coil_w = inner_pf_coil_width\n",
    "        self._inner_pf_coil_h = inner_pf_coil_height\n",
    "        self._inner_pf_coil_ct = inner_pf_coil_case_thickness\n",
    "        self._inner_tf_coil_cp = inner_pf_coil_center_points\n",
    "        self._divertor_height_full = divertor_height_full\n",
    "        self._inner_bore_radius = inner_bore_radius\n",
    "\n",
    "        if outer_tf_coil_thickness == None:\n",
    "            self._outer_tf_coil_thickness = inner_tf_coil_thickness\n",
    "        else:\n",
    "            self._outer_tf_coil_thickness = outer_tf_coil_thickness\n",
    "\n",
    "        self._pf_enabled = pf_enabled\n",
    "\n",
    "        if self._pf_enabled == True:\n",
    "            self._pf_coil_heights = pf_coil_heights\n",
    "            self._pf_coil_widths = pf_coil_widths\n",
    "            self._pf_coil_center_points = pf_coil_center_points\n",
    "            self._pf_casing_thickness = pf_coil_casing_thickness\n",
    "\n",
    "        self._rotation_angle = rotation_angle\n",
    "        self.show_plasma = show_plasma\n",
    "        self.low_aspect = low_aspect\n",
    "        self._number_of_coils = number_of_coils\n",
    "        self._tf_width = tf_width\n",
    "        self._port_side_length = port_side_length\n",
    "        self._port_thickness = port_thickness\n",
    "        self._ports_enable = ports_enabled\n",
    "\n",
    "\n",
    "        ########### Calculating plasma geometry from parameters above ###########\n",
    "\n",
    "        ### Adjust a gap between inner TF leg and vacuum vessel to accomodate a wider range of thicknesses\n",
    "        core_width = self._inner_tf_coil_thickness + self._vacuum_vessel_thickness + self._central_shield_thickness\n",
    "        blanket_width = self._inner_wall_thickness + self._blanket_thickness + self._rear_wall_thickness\n",
    "        wdth_diff = blanket_width - core_width\n",
    "\n",
    "        if wdth_diff > 0:\n",
    "            self._inner_leg_to_vacuum_inner_wall_gap = wdth_diff\n",
    "        else:\n",
    "            self._inner_leg_to_vacuum_inner_wall_gap = 0\n",
    "\n",
    "        ### Define Equatorial points\n",
    "        self._inner_equatorial_point = self._inner_bore_radius \\\n",
    "            + self._inner_tf_coil_thickness \\\n",
    "            + self._vacuum_vessel_thickness \\\n",
    "            + self._central_shield_thickness \\\n",
    "            + self._wall_to_plasma_gap \\\n",
    "            + self._inner_leg_to_vacuum_inner_wall_gap\n",
    "        if self.low_aspect == False:\n",
    "            self._inner_equatorial_point += self._inner_wall_thickness \\\n",
    "            + self._blanket_thickness \\\n",
    "            + self._rear_wall_thickness\n",
    "            \n",
    "        self._outer_equatorial_point = self._inner_equatorial_point + self._plasma_radial_thickness\n",
    "\n",
    "        self._major_radius = (self._outer_equatorial_point + self._inner_equatorial_point)/2\n",
    "        self._minor_radius = (self._major_radius - self._inner_equatorial_point)\n",
    "        print(\"Aspect Ratio = {:.2f}\".format(self._major_radius/self._minor_radius))\n",
    "        print(\"Major Radius = {:.2f}\".format(self._major_radius))\n",
    "        print(\"Minor Radius = {:.2f}\".format(self._minor_radius))\n",
    "        \n",
    "        \n",
    "    @property\n",
    "    def vacuum_vessel_thickness(self):\n",
    "        return self._vacuum_vessel_thickness\n",
    "    \n",
    "    @property\n",
    "    def inner_equatorial_point(self):\n",
    "        return self._inner_equatorial_point\n",
    "    \n",
    "    @property\n",
    "    def outer_equatorial_point(self):\n",
    "        return self._outer_equatorial_point\n",
    "        \n",
    "    @property\n",
    "    def tf_thickness(self):\n",
    "        return self._inner_tf_coil_thickness\n",
    "\n",
    "    @property\n",
    "    def major_radius(self):\n",
    "        return self._major_radius\n",
    "\n",
    "    @property\n",
    "    def minor_radius(self):\n",
    "        return self._minor_radius\n",
    "    \n",
    "    @property\n",
    "    def blanket_volume(self):\n",
    "        print(\"Breeder Volume:\", self._breeder_blanket.volume)\n",
    "        return self._breeder_blanket.volume\n",
    "\n",
    "    \n",
    "\n",
    "    def create_solid(self):\n",
    "\n",
    "        shapes_and_components = []\n",
    "\n",
    "        self._make_plasma()\n",
    "        self._make_vertical_build()\n",
    "        self._make_radial_build()\n",
    "\n",
    "        \n",
    "        if self.show_plasma == True:\n",
    "            shapes_and_components.append(self._make_plasma())\n",
    "        else:\n",
    "            print(\"Plasma is excluded from the model.\")\n",
    "        \n",
    "        shapes_and_components += self._make_tf_inner_leg()\n",
    "        shapes_and_components += self._make_vacuum_vessel_inner_wall()\n",
    "        shapes_and_components += self._make_inner_shield()\n",
    "\n",
    "        shapes_and_components += self._make_blankets()\n",
    "        shapes_and_components += self._make_divertor()\n",
    "        shapes_and_components += self._make_tf_coils()\n",
    "        #shapes_and_components += self._make_ports()\n",
    "        shapes_and_components += self._make_vacuum_vessel()\n",
    "\n",
    "        if self._ports_enable == True:\n",
    "            shapes_and_components += self._make_ports()\n",
    "\n",
    "        if self._pf_enabled == True:\n",
    "            shapes_and_components += self._make_pf_coils()\n",
    "        \n",
    "\n",
    "        self.shapes_and_components = shapes_and_components\n",
    "\n",
    "        \n",
    "\n",
    "    def _make_plasma(self):\n",
    "        plasma = paramak.Plasma(\n",
    "            major_radius=self._major_radius,\n",
    "            minor_radius=self._minor_radius,\n",
    "            elongation=self._elongation,\n",
    "            triangularity=self._triangularity,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            color=(0,0.5,0.5)\n",
    "        )\n",
    "        self._plasma = plasma\n",
    "        return self._plasma\n",
    "\n",
    "    def _make_vertical_build(self):\n",
    "\n",
    "        ### Above the plasma ###\n",
    "\n",
    "        # Inner wall\n",
    "        self._inner_wall_start_height = self._plasma.high_point[1] + self._wall_to_plasma_gap\n",
    "        self._inner_wall_end_height = self._inner_wall_start_height + self._inner_wall_thickness\n",
    "        # Blanket\n",
    "        self._blanket_start_height_top = self._inner_wall_end_height\n",
    "        self._blanket_end_height_top = self._blanket_start_height_top + self._blanket_thickness\n",
    "        # Rear wall\n",
    "        self._rear_wall_start_height_top = self._blanket_end_height_top\n",
    "        self._rear_wall_end_height_top = self._rear_wall_start_height_top + self._rear_wall_thickness\n",
    "        # Divertor\n",
    "        self._divertor_start_height = (self._plasma.high_point[1])\n",
    "        self._divertor_end_height_top = self._divertor_start_height + self._divertor_height_full\n",
    "\n",
    "        ### Diverter height check ###\n",
    "        min_div_h = self._rear_wall_end_height_top - self._divertor_start_height\n",
    "\n",
    "        if (min_div_h > self._divertor_height_full):\n",
    "            print(\"Set divertor height is too low. Diverter height is set to minimum of {:.2f} cm\".format((min_div_h)))\n",
    "            self._divertor_end_height_top = self._divertor_start_height + min_div_h\n",
    "\n",
    "        # Vacuum Vessel Inner Wall\n",
    "        self._vacuum_vessel_start_height = self._divertor_end_height_top\n",
    "        self._vacuum_vessel_end_height = self._vacuum_vessel_start_height \\\n",
    "                                        + self._vacuum_vessel_thickness\n",
    "        # Central Heights\n",
    "        self._inner_tf_leg_height = self._vacuum_vessel_end_height * 2\n",
    "        self._vacuum_vessel_height = self._vacuum_vessel_start_height * 2\n",
    "        self._inner_shield_height = self._vacuum_vessel_start_height * 2\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        # Outer Blanket Height\n",
    "        self._outer_blanket_height = self._inner_shield_height - (2 * self._divertor_height_full)\n",
    "        if self._outer_blanket_height < 0:\n",
    "            raise ValueError(\"The divertors are overlapping at the center plane.\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    def _make_radial_build(self):\n",
    "        # Bore\n",
    "        self._inner_bore_start_rad = 0\n",
    "        self._inner_bore_stop_rad = self._inner_bore_radius\n",
    "        # Inner TF Coil\n",
    "        self._tf_inner_leg_start_rad = self._inner_bore_stop_rad\n",
    "        self._tf_inner_leg_end_rad = self._tf_inner_leg_start_rad + self._inner_tf_coil_thickness\n",
    "        # Vacuum Vessel Inner wall\n",
    "        self._vacuum_vessel_inwall_start_rad = self._tf_inner_leg_end_rad + self._inner_leg_to_vacuum_inner_wall_gap\n",
    "        self._vacuum_vessel_inwall_end_rad = self._vacuum_vessel_inwall_start_rad + self._vacuum_vessel_thickness\n",
    "        # Central Column Shield\n",
    "        self._inner_shield_start_rad = self._vacuum_vessel_inwall_end_rad\n",
    "        self._inner_shield_end_rad = self._inner_shield_start_rad + self._central_shield_thickness\n",
    "        # Blanket Offset\n",
    "        self._blanket_offset = self._wall_to_plasma_gap + self._inner_wall_thickness        \n",
    "        # Rear Wall offset\n",
    "        self._rear_wall_plasma_offset = self._wall_to_plasma_gap + self._blanket_thickness + self._inner_wall_thickness\n",
    "        \n",
    "\n",
    "        # Inner PF Coils\n",
    "        if self._inner_pf_coil_w is not None:    \n",
    "            self._inner_pf_thickness = max(self._inner_pf_coil_w)\n",
    "            self._inner_pf_case_thickness = max(self._inner_pf_coil_ct)\n",
    "        else:\n",
    "            self._inner_pf_thickness = 0\n",
    "            self._inner_pf_case_thickness = 0\n",
    "\n",
    "\n",
    "        \n",
    "        ### Run check for diverter parameters ###\n",
    "\n",
    "        full_outer_blanket_rad = (self._major_radius + self._minor_radius + self._wall_to_plasma_gap + self._inner_wall_thickness \\\n",
    "                    + self._blanket_thickness + self._rear_wall_thickness)\n",
    "\n",
    "        if self.low_aspect == False:\n",
    "            full_outer_blanket_rad += self._inner_wall_thickness \\\n",
    "                                    + self._blanket_thickness \\\n",
    "                                    + self._rear_wall_thickness\n",
    "        \n",
    "        width_parameter_difference = full_outer_blanket_rad - self._plasma.high_point[0]\n",
    "        \n",
    "        if self._divertor_radial_thickness < width_parameter_difference:\n",
    "            print(\"The given radial thickness of the divertor is too small. Diverter set to minimum radial thickness of {:.2f} cm\".format(width_parameter_difference))\n",
    "            self._divertor_radial_thickness = width_parameter_difference\n",
    "\n",
    "        ### Divertor parts ###\n",
    "        self._divertor_start_rad = self._plasma.high_point[0]\n",
    "        self._divertor_end_rad = self._divertor_start_rad + self._divertor_radial_thickness\n",
    "\n",
    "        # Vacuum Vessel Body\n",
    "        self._vacuum_vessel_body_start_rad = self._divertor_end_rad\n",
    "        self._vacuum_vessel_body_end_rad = self._vacuum_vessel_body_start_rad + self._vacuum_vessel_thickness\n",
    "\n",
    "\n",
    "    def _make_tf_inner_leg(self):\n",
    "        \n",
    "        self._bore_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_tf_leg_height+10,\n",
    "            inner_radius=0,\n",
    "            outer_radius=self._inner_bore_stop_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "        )\n",
    "\n",
    "        self._tf_inner_leg = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_tf_leg_height,\n",
    "            inner_radius=0,\n",
    "            outer_radius=self._tf_inner_leg_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            stp_filename=\"tf_inner_leg.stp\",\n",
    "            stl_filename=\"tf_inner_leg.stl\",\n",
    "            name=\"tf_inner_leg\",\n",
    "            material_tag=\"inboard_tf_coils_mat\",\n",
    "            cut=[self._bore_cutter],\n",
    "            color=(0.2,1,0.2),\n",
    "        )\n",
    "        \n",
    "        self._tf_inner_leg.show()\n",
    "        return [self._tf_inner_leg]\n",
    "\n",
    "\n",
    "    def _make_vacuum_vessel_inner_wall(self):\n",
    "\n",
    "        self._vacuum_vessel_inner_wall = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._vacuum_vessel_height,\n",
    "            inner_radius=self._vacuum_vessel_inwall_start_rad,\n",
    "            outer_radius=self._vacuum_vessel_inwall_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            stp_filename=\"vacuum_vessel_inner_wall.stp\",\n",
    "            stl_filename=\"vacuum_vessel_inner_wall.stl\",\n",
    "            name=\"vacuum_vessel_inner_wall\",\n",
    "            material_tag=\"vacuum_vessel_mat\",\n",
    "            color=(0.5,0.5,0.5)\n",
    "        )\n",
    "\n",
    "        return [self._vacuum_vessel_inner_wall]\n",
    "\n",
    "    def _make_inner_shield(self):\n",
    "\n",
    "        self._inner_shield = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_shield_height,\n",
    "            inner_radius=self._inner_shield_start_rad,\n",
    "            outer_radius=self._inner_shield_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            stp_filename=\"inner_shield.stp\",\n",
    "            stl_filename=\"inner_shield.stl\",\n",
    "            name=\"inner_shield\",\n",
    "            material_tag=\"center_column_shield_mat\",\n",
    "            color=(1,0.7,0.5)\n",
    "        )\n",
    "\n",
    "        return [self._inner_shield]\n",
    "\n",
    "\n",
    "    def _make_blankets(self):\n",
    "\n",
    "        ### Cutters ###\n",
    "\n",
    "\n",
    "        self._divertor_cutter_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._divertor_start_height * 2,\n",
    "            inner_radius=0,\n",
    "            outer_radius=self._divertor_end_rad + 10\n",
    "        )\n",
    "\n",
    "        self._divertor_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_tf_leg_height + 10,\n",
    "            inner_radius=self._divertor_start_rad,\n",
    "            outer_radius=self._divertor_end_rad,\n",
    "            cut=[self._divertor_cutter_cutter]\n",
    "        )\n",
    "\n",
    "\n",
    "        central_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_tf_leg_height + 10, #for overlap\n",
    "            inner_radius=0,\n",
    "            outer_radius=self._inner_shield_end_rad,\n",
    "            union=[self._divertor_cutter]\n",
    "        )\n",
    "\n",
    "\n",
    "\n",
    "        self._rear_wall = paramak.BlanketFP(\n",
    "            thickness=self._rear_wall_thickness,\n",
    "            start_angle=180,\n",
    "            stop_angle=-180,\n",
    "            plasma=self._make_plasma(),\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            offset_from_plasma=[self._rear_wall_plasma_offset + self._wall_to_plasma_gap, self._rear_wall_plasma_offset, self._rear_wall_plasma_offset + self._wall_to_plasma_gap],\n",
    "            material_tag=\"blanket_rear_wall_mat\",\n",
    "            stp_filename=\"blanket_rear_wall.stp\",\n",
    "            stl_filename=\"blanket_rear_wall.stl\",\n",
    "            name=\"blanket_rear_wall\",\n",
    "            cut=[central_cutter],\n",
    "            color=(0.3,0.3,0.3)\n",
    "\n",
    "        )\n",
    "\n",
    "        self._breeder_blanket = paramak.BlanketFP(\n",
    "            thickness=self._blanket_thickness,\n",
    "            start_angle=180,\n",
    "            stop_angle=-180,\n",
    "            plasma=self._make_plasma(),\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            offset_from_plasma=[self._blanket_offset + self._wall_to_plasma_gap, self._blanket_offset, self._blanket_offset + self._wall_to_plasma_gap],\n",
    "            material_tag=\"blanket_mat\",\n",
    "            stp_filename=\"blanket.stp\",\n",
    "            stl_filename=\"blanket.stl\",\n",
    "            name=\"blanket\",\n",
    "            cut=[central_cutter],\n",
    "            color=(0.5,1,0.5)\n",
    "\n",
    "        )\n",
    "\n",
    "        self._inner_wall = paramak.BlanketFP(\n",
    "            thickness=self._inner_wall_thickness,\n",
    "            start_angle=180,\n",
    "            stop_angle=-180,\n",
    "            plasma=self._make_plasma(),\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            offset_from_plasma=[self._wall_to_plasma_gap*2, self._wall_to_plasma_gap, self._wall_to_plasma_gap*2],\n",
    "            material_tag=\"firstwall_mat\",\n",
    "            stp_filename=\"firstwall.stp\",\n",
    "            stl_filename=\"firstwall.stl\",\n",
    "            name=\"firstwall\",\n",
    "            cut=[central_cutter],\n",
    "            color=(0.3,0.3,0.3)\n",
    "\n",
    "        )\n",
    "\n",
    "        return [self._rear_wall,self._breeder_blanket,self._inner_wall]\n",
    "\n",
    "\n",
    "\n",
    "    def _make_divertor(self):\n",
    "\n",
    "\n",
    "        self._divertor_extention_cutter = paramak.BlanketFP(\n",
    "            thickness= -self._wall_to_plasma_gap * 2,\n",
    "            start_angle=180,\n",
    "            stop_angle=-180,\n",
    "            plasma=self._make_plasma(),\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            offset_from_plasma=[self._wall_to_plasma_gap * 2, self._wall_to_plasma_gap, self._wall_to_plasma_gap * 2],\n",
    "        )\n",
    "    \n",
    "        self._divertor_midplane_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height = (self._divertor_start_height) * 2,\n",
    "            inner_radius=self._divertor_start_rad,\n",
    "            outer_radius=self._divertor_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "        )\n",
    "        \n",
    "        self._divertor = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._divertor_end_height_top * 2,\n",
    "            inner_radius=self._divertor_start_rad,\n",
    "            outer_radius=self._divertor_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            cut=[self._divertor_extention_cutter, self._divertor_midplane_cutter ],\n",
    "            color=(1,0.2,0.2),\n",
    "            material_tag=\"divertor_mat\",\n",
    "            stp_filename=\"divertor.stp\",\n",
    "            stl_filename=\"divertor.stl\",\n",
    "            name=\"divertor\"\n",
    "        )\n",
    "\n",
    "        return [self._divertor]\n",
    "\n",
    "    def _make_vacuum_vessel(self):\n",
    "\n",
    "        vac_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._vacuum_vessel_height,\n",
    "            inner_radius=self._vacuum_vessel_inwall_start_rad,\n",
    "            outer_radius=self._vacuum_vessel_body_start_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            color=(0.5,0.5,0.5)\n",
    "        )\n",
    "\n",
    "        if self._ports_enable == True:\n",
    "            cutting_list = [vac_cutter,self._port_cutter_top,self._port_cutter_mid,self._port_cutter_bot]\n",
    "        else:\n",
    "            cutting_list = [vac_cutter]\n",
    "\n",
    "        self._vacuum_vessel_body = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._vacuum_vessel_height + (self._vacuum_vessel_thickness * 2),\n",
    "            inner_radius=self._vacuum_vessel_inwall_start_rad,\n",
    "            outer_radius=self._vacuum_vessel_body_end_rad,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            stp_filename=\"vacuum_vessel_body.stp\",\n",
    "            stl_filename=\"vacuum_vessel_body.stl\",\n",
    "            name=\"vacuum_vessel_body\",\n",
    "            material_tag=\"vacuum_vessel_mat\",\n",
    "            cut=cutting_list,\n",
    "            color=(0.5,0.5,0.5)\n",
    "        )\n",
    "\n",
    "        return [self._vacuum_vessel_body]\n",
    "\n",
    "    def _make_tf_coils(self):\n",
    "\n",
    "        _tf_coils_init = ToroidalFieldCoilRectangleRoundCorners(\n",
    "            with_inner_leg=False,\n",
    "            lower_inner_coordinates=(self._inner_bore_stop_rad, -self._inner_tf_leg_height/2),\n",
    "            mid_point_coordinates=(self._vacuum_vessel_body_end_rad, 0),\n",
    "            thickness=self._outer_tf_coil_thickness,\n",
    "            number_of_coils=self._number_of_coils,\n",
    "            distance=self._tf_width,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            color=(0.2,1,0.2)\n",
    "        )\n",
    "\n",
    "        self._small_rad_displacement = _tf_coils_init.analyse_attributes[2]\n",
    "        \n",
    "        self._tf_coils = ToroidalFieldCoilRectangleRoundCorners(\n",
    "            with_inner_leg=False,\n",
    "            lower_inner_coordinates=(self._inner_bore_stop_rad, -self._inner_tf_leg_height/2),\n",
    "            mid_point_coordinates=(self._vacuum_vessel_body_end_rad + self._small_rad_displacement, 0),\n",
    "            thickness=self._outer_tf_coil_thickness,\n",
    "            number_of_coils=self._number_of_coils,\n",
    "            distance=self._tf_width,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "            stp_filename=\"tf_coil_outer.stp\",\n",
    "            stl_filename=\"tf_coil_outer.stl\",\n",
    "            name=\"tf_coil_outer\",\n",
    "            material_tag=\"inboard_tf_coils_mat\",\n",
    "            color=(0.2,1,0.2)\n",
    "        )\n",
    "\n",
    "        return [self._tf_coils]\n",
    "\n",
    "\n",
    "    def _make_ports(self):\n",
    "\n",
    "        _start_angle = (360/self._number_of_coils)/2\n",
    "        _end_angle = 360 + _start_angle\n",
    "        _port_angles = np.linspace(_start_angle, _end_angle, self._number_of_coils+1)\n",
    "\n",
    "        self._port_cutter_top = paramak.PortCutterRectangular(\n",
    "            height=self._port_side_length,\n",
    "            width=self._port_side_length,\n",
    "            distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._tf_coil_outer_end_rad,\n",
    "            extrusion_start_offset=1,\n",
    "            center_point=(self._plasma.high_point[1] - self._port_side_length,0),\n",
    "            azimuth_placement_angle=_port_angles,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "\n",
    "        )\n",
    "\n",
    "        self._port_cutter_mid = paramak.PortCutterRectangular(\n",
    "            height=self._port_side_length,\n",
    "            width=self._port_side_length,\n",
    "            distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._vacuum_vessel_body_end_rad,\n",
    "            extrusion_start_offset=1,\n",
    "            center_point=(0,0),\n",
    "            azimuth_placement_angle=_port_angles,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "\n",
    "        )\n",
    "\n",
    "        self._port_cutter_bot = paramak.PortCutterRectangular(\n",
    "            height=self._port_side_length,\n",
    "            width=self._port_side_length,\n",
    "            distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._vacuum_vessel_body_end_rad,\n",
    "            extrusion_start_offset=1,\n",
    "            center_point=(-(self._plasma.high_point[1] - self._port_side_length),0),\n",
    "            azimuth_placement_angle=_port_angles,\n",
    "            rotation_angle=self._rotation_angle,\n",
    "\n",
    "        )\n",
    "\n",
    "        central_port_cutter = paramak.CenterColumnShieldCylinder(\n",
    "            height=self._inner_tf_leg_height,\n",
    "            inner_radius=0,\n",
    "            outer_radius=self._vacuum_vessel_body_end_rad,\n",
    "        )\n",
    "        \n",
    "\n",
    "        #self._port_top = paramak.PortCutterRectangular(\n",
    "        #    height=self._port_side_length,\n",
    "        #    width=self._port_side_length,\n",
    "        #    distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._vacuum_vessel_body_end_rad,\n",
    "        #    extrusion_start_offset=1,\n",
    "        #    center_point=(self._plasma.high_point[1] - self._port_side_length,0),\n",
    "        #    azimuth_placement_angle=_port_angles,\n",
    "        #    rotation_angle=self._rotation_angle,\n",
    "        #    cut=[central_port_cutter, self._port_cutter_top]\n",
    "        #\n",
    "        #)\n",
    "        #\n",
    "        #self._port_mid = paramak.PortCutterRectangular(\n",
    "        #    height=self._port_side_length,\n",
    "        #    width=self._port_side_length,\n",
    "        #    distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._vacuum_vessel_body_end_rad,\n",
    "        #    extrusion_start_offset=1,\n",
    "        #    center_point=(0,0),\n",
    "        #    azimuth_placement_angle=_port_angles,\n",
    "        #    rotation_angle=self._rotation_angle,\n",
    "        #    cut=[central_port_cutter, self._port_cutter_mid]\n",
    "        #       \n",
    "        #)\n",
    "        #\n",
    "        #self._port_bot = paramak.PortCutterRectangular(\n",
    "        #    height=self._port_side_length + self._port_thickness,\n",
    "        #    width=self._port_side_length + self._port_thickness,\n",
    "        #    distance=self._small_rad_displacement + self._outer_tf_coil_thickness + self._vacuum_vessel_body_end_rad,\n",
    "        #    extrusion_start_offset=1,\n",
    "        #    center_point=(-(self._plasma.high_point[1] - self._port_side_length),0),\n",
    "        #    azimuth_placement_angle=_port_angles,\n",
    "        #    rotation_angle=self._rotation_angle,\n",
    "        #    cut=[central_port_cutter, self._port_cutter_bot]\n",
    "        #\n",
    "        #)\n",
    "\n",
    "        return []\n",
    "\n",
    "    def _make_pf_coils(self):\n",
    "\n",
    "        self._pf_coils = paramak.PoloidalFieldCoilSet(\n",
    "            heights=self._pf_coil_heights,\n",
    "            widths=self._pf_coil_widths,\n",
    "            center_points=self._pf_coil_center_points,\n",
    "            stp_filename=\"pf_coil_set.stp\",\n",
    "            stl_filename=\"pf_coil_set.stl\",\n",
    "            name=\"pf_coil_set\",\n",
    "            color=(0.7,0.7,0.2),\n",
    "            rotation_angle=self._rotation_angle\n",
    "\n",
    "        )\n",
    "\n",
    "        self._pf_casing = paramak.PoloidalFieldCoilCaseSet(\n",
    "            heights=self._pf_coil_heights,\n",
    "            widths=self._pf_coil_widths,\n",
    "            center_points=self._pf_coil_center_points,\n",
    "            casing_thicknesses=self._pf_casing_thickness,\n",
    "            stp_filename=\"pf_coil_set_case.stp\",\n",
    "            stl_filename=\"pf_coil_set_case.stl\",\n",
    "            name=\"pf_coil_set_case\",\n",
    "            color=(0.7,0.5,0.2),\n",
    "            rotation_angle=self._rotation_angle\n",
    "        )\n",
    "        return [self._pf_coils,self._pf_casing]\n",
    "\n",
    "\n",
    "    \n",
    "ys = []\n",
    "#for i in np.arange(0,18,1):\n",
    "obj = NegativeTriangularityReactor(\n",
    "        inner_bore_radius=30,\n",
    "        inner_tf_coil_thickness=100,\n",
    "        vacuum_vessel_thickness=50,\n",
    "        central_shield_thickness=2,\n",
    "        wall_to_plasma_gap=5,\n",
    "        plasma_radial_thickness=650,\n",
    "        elongation=2,\n",
    "        triangularity=.6,\n",
    "        inner_wall_thickness=2,\n",
    "        blanket_thickness=105,\n",
    "        rear_wall_thickness=2,\n",
    "        divertor_radial_thickness=350,\n",
    "        divertor_height_full=350,\n",
    "        rotation_angle=180,\n",
    "        tf_width=75,\n",
    "        number_of_coils=12,\n",
    "        port_side_length=0,\n",
    "        port_thickness=1,\n",
    "        pf_coil_heights=[],\n",
    "        pf_coil_widths=[],\n",
    "        pf_coil_center_points=[],\n",
    "        pf_coil_casing_thickness=[],\n",
    "\n",
    "        show_plasma=True,\n",
    "        low_aspect=True,\n",
    "        ports_enabled=False,\n",
    "        pf_enabled=False,\n",
    "\n",
    ")\n",
    "obj.create_solid()\n",
    "#ys.append(obj.blanket_volume)\n",
    "\n",
    "obj.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
